export const countriesName = [
  "AF",
  "AL",
  "DZ",
  "AS",
  "AD",
  "AO",
  "AI",
  "AG",
  "AR",
  "AM",
  "AW",
  "AU",
  "AT",
  "AZ",
  "BS",
  "BH",
  "BD",
  "BB",
  "BY",
  "BE",
  "BZ",
  "BJ",
  "BM",
  "BT",
  "BO",
  "BA",
  "BW",
  "BR",
  "IO",
  "BG",
  "BF",
  "BI",
  "KH",
  "CM",
  "CA",
  "CV",
  "KY",
  "CF",
  "TD",
  "CL",
  "CN",
  "CO",
  "KM",
  "CG",
  "CD",
  "CK",
  "CR",
  "CI",
  "HR",
  "CU",
  "CW",
  "CY",
  "CZ",
  "DK",
  "DJ",
  "DM",
  "DO",
  "EC",
  "EG",
  "SV",
  "GQ",
  "ER",
  "EE",
  "ET",
  "FK",
  "FO",
  "FJ",
  "FI",
  "FR",
  "PF",
  "GA",
  "GM",
  "GE",
  "DE",
  "GH",
  "GI",
  "GR",
  "GL",
  "GD",
  "GU",
  "GT",
  "GG",
  "GN",
  "GW",
  "HT",
  "HN",
  "HK",
  "HU",
  "IS",
  "IN",
  "ID",
  "IR",
  "IQ",
  "IE",
  "IM",
  "IL",
  "IT",
  "JM",
  "JP",
  "JE",
  "JO",
  "KZ",
  "KE",
  "KI",
  "KP",
  "KR",
  "KW",
  "KG",
  "LA",
  "LV",
  "LB",
  "LS",
  "LR",
  "LY",
  "LI",
  "LT",
  "LU",
  "MO",
  "MK",
  "MG",
  "MW",
  "MY",
  "MV",
  "ML",
  "MT",
  "MH",
  "MQ",
  "MR",
  "MU",
  "MX",
  "FM",
  "MD",
  "MC",
  "MN",
  "ME",
  "MS",
  "MA",
  "MZ",
  "MM",
  "NA",
  "NR",
  "NP",
  "NL",
  "NZ",
  "NI",
  "NE",
  "NG",
  "NU",
  "NF",
  "MP",
  "NO",
  "OM",
  "PK",
  "PW",
  "PS",
  "PA",
  "PG",
  "PY",
  "PE",
  "PH",
  "PN",
  "PL",
  "PT",
  "PR",
  "QA",
  "RO",
  "RU",
  "RW",
  "KN",
  "LC",
  "WS",
  "SM",
  "ST",
  "SA",
  "SN",
  "RS",
  "SC",
  "SL",
  "SG",
  "SX",
  "SK",
  "SI",
  "SB",
  "SO",
  "ZA",
  "SS",
  "ES",
  "LK",
  "SD",
  "SR",
  "SZ",
  "SE",
  "CH",
  "SY",
  "TW",
  "TJ",
  "TZ",
  "TH",
  "TG",
  "TK",
  "TO",
  "TT",
  "TN",
  "TR",
  "TM",
  "TC",
  "TV",
  "UG",
  "UA",
  "AE",
  "GB",
  "US",
  "UY",
  "UZ",
  "VU",
  "VE",
  "VN",
  "VI",
  "YE",
  "ZM",
  "ZW",
];
export const countriesLabel: any = {
  AF: { primary: "Afghanistan", secondary: "+93" },
  AL: { primary: "Albania", secondary: "+355" },
  DZ: { primary: "Algeria", secondary: "+213" },
  AS: { primary: "American Samoa", secondary: "+1 684" },
  AD: { primary: "Andorra", secondary: "+376" },
  AO: { primary: "Angola", secondary: "+244" },
  AI: { primary: "Anguilla", secondary: "+1 264" },
  AG: { primary: "Antigua and Barbuda", secondary: "+1 268" },
  AR: { primary: "Argentina", secondary: "+54" },
  AM: { primary: "Armenia", secondary: "+374" },
  AW: { primary: "Aruba", secondary: "+297" },
  AU: { primary: "Australia", secondary: "+61" },
  AT: { primary: "Austria", secondary: "+43" },
  AZ: { primary: "Azerbaijan", secondary: "+994" },
  BS: { primary: "Bahamas", secondary: "+1 242" },
  BH: { primary: "Bahrain", secondary: "+973" },
  BD: { primary: "Bangladesh", secondary: "+880" },
  BB: { primary: "Barbados", secondary: "+1 246" },
  BY: { primary: "Belarus", secondary: "+375" },
  BE: { primary: "Belgium", secondary: "+32" },
  BZ: { primary: "Belize", secondary: "+501" },
  BJ: { primary: "Benin", secondary: "+229" },
  BM: { primary: "Bermuda", secondary: "+1 441" },
  BT: { primary: "Bhutan", secondary: "+975" },
  BO: { primary: "Bolivia, Plurinational State of", secondary: "+591" },
  BA: { primary: "Bosnia and Herzegovina", secondary: "+387" },
  BW: { primary: "Botswana", secondary: "+267" },
  BR: { primary: "Brazil", secondary: "+55" },
  IO: { primary: "British Indian Ocean Territory", secondary: "+246" },
  BG: { primary: "Bulgaria", secondary: "+359" },
  BF: { primary: "Burkina Faso", secondary: "+226" },
  BI: { primary: "Burundi", secondary: "+257" },
  KH: { primary: "Cambodia", secondary: "+855" },
  CM: { primary: "Cameroon", secondary: "+237" },
  CA: { primary: "Canada", secondary: "+1" },
  CV: { primary: "Cape Verde", secondary: "+238" },
  KY: { primary: "Cayman Islands", secondary: "+1 345" },
  CF: { primary: "Central African Republic", secondary: "+236" },
  TD: { primary: "Chad", secondary: "+235" },
  CL: { primary: "Chile", secondary: "+56" },
  CN: { primary: "China", secondary: "+86" },
  CO: { primary: "Colombia", secondary: "+57" },
  KM: { primary: "Comoros", secondary: "+269" },
  CG: { primary: "Congo", secondary: "+242" },
  CD: { primary: "Democratic Republic of the Congo", secondary: "+243" },
  CK: { primary: "Cook Islands", secondary: "+682" },
  CR: { primary: "Costa Rica", secondary: "+506" },
  CI: { primary: "Côte d'Ivoire", secondary: "+225" },
  HR: { primary: "Croatia", secondary: "+385" },
  CU: { primary: "Cuba", secondary: "+53" },
  CW: { primary: "Curaçao", secondary: "+599" },
  CY: { primary: "Cyprus", secondary: "+357" },
  CZ: { primary: "Czech Republic", secondary: "+420" },
  DK: { primary: "Denmark", secondary: "+45" },
  DJ: { primary: "Djibouti", secondary: "+253" },
  DM: { primary: "Dominica", secondary: "+1 767" },
  DO: { primary: "Dominican Republic", secondary: "+1 809" },
  EC: { primary: "Ecuador", secondary: "+593" },
  EG: { primary: "Egypt", secondary: "+20" },
  SV: { primary: "El Salvador", secondary: "+503" },
  GQ: { primary: "Equatorial Guinea", secondary: "+240" },
  ER: { primary: "Eritrea", secondary: "+291" },
  EE: { primary: "Estonia", secondary: "+372" },
  ET: { primary: "Ethiopia", secondary: "+251" },
  FK: { primary: "Falkland Islands (Malvinas)", secondary: "+500" },
  FO: { primary: "Faroe Islands", secondary: "+298" },
  FJ: { primary: "Fiji", secondary: "+679" },
  FI: { primary: "Finland", secondary: "+358" },
  FR: { primary: "France", secondary: "+33" },
  PF: { primary: "French Polynesia", secondary: "+689" },
  GA: { primary: "Gabon", secondary: "+241" },
  GM: { primary: "Gambia", secondary: "+220" },
  GE: { primary: "Georgia", secondary: "+995" },
  DE: { primary: "Germany", secondary: "+49" },
  GH: { primary: "Ghana", secondary: "+233" },
  GI: { primary: "Gibraltar", secondary: "+350" },
  GR: { primary: "Greece", secondary: "+30" },
  GL: { primary: "Greenland", secondary: "+299" },
  GD: { primary: "Grenada", secondary: "+1 473" },
  GU: { primary: "Guam", secondary: "+1 671" },
  GT: { primary: "Guatemala", secondary: "+502" },
  GG: { primary: "Guernsey", secondary: "+44" },
  GN: { primary: "Guinea", secondary: "+224" },
  GW: { primary: "Guinea-Bissau", secondary: "+245" },
  HT: { primary: "Haiti", secondary: "+509" },
  HN: { primary: "Honduras", secondary: "+504" },
  HK: { primary: "Hong Kong", secondary: "+852" },
  HU: { primary: "Hungary", secondary: "+36" },
  IS: { primary: "Iceland", secondary: "+354" },
  IN: { primary: "India", secondary: "+91" },
  ID: { primary: "Indonesia", secondary: "+62" },
  IR: { primary: "Iran, Islamic Republic of", secondary: "+98" },
  IQ: { primary: "Iraq", secondary: "+964" },
  IE: { primary: "Ireland", secondary: "+353" },
  IM: { primary: "Isle of Man", secondary: "+44" },
  IL: { primary: "Israel", secondary: "+972" },
  IT: { primary: "Italy", secondary: "+39" },
  JM: { primary: "Jamaica", secondary: "+1 876" },
  JP: { primary: "Japan", secondary: "+81" },
  JE: { primary: "Jersey", secondary: "+44" },
  JO: { primary: "Jordan", secondary: "+962" },
  KZ: { primary: "Kazakhstan", secondary: "+7" },
  KE: { primary: "Kenya", secondary: "+254" },
  KI: { primary: "Kiribati", secondary: "+686" },
  KP: { primary: "North Korea", secondary: "+850" },
  KR: { primary: "South Korea", secondary: "+82" },
  KW: { primary: "Kuwait", secondary: "+965" },
  KG: { primary: "Kyrgyzstan", secondary: "+996" },
  LA: { primary: "Lao People's Democratic Republic", secondary: "+856" },
  LV: { primary: "Latvia", secondary: "+371" },
  LB: { primary: "Lebanon", secondary: "+961" },
  LS: { primary: "Lesotho", secondary: "+266" },
  LR: { primary: "Liberia", secondary: "+231" },
  LY: { primary: "Libya", secondary: "+218" },
  LI: { primary: "Liechtenstein", secondary: "+423" },
  LT: { primary: "Lithuania", secondary: "+370" },
  LU: { primary: "Luxembourg", secondary: "+352" },
  MO: { primary: "Macao", secondary: "+853" },
  MK: { primary: "Republic of Macedonia", secondary: "+389" },
  MG: { primary: "Madagascar", secondary: "+261" },
  MW: { primary: "Malawi", secondary: "+265" },
  MY: { primary: "Malaysia", secondary: "+60" },
  MV: { primary: "Maldives", secondary: "+960" },
  ML: { primary: "Mali", secondary: "+223" },
  MT: { primary: "Malta", secondary: "+356" },
  MH: { primary: "Marshall Islands", secondary: "+692" },
  MQ: { primary: "Martinique", secondary: "+596" },
  MR: { primary: "Mauritania", secondary: "+222" },
  MU: { primary: "Mauritius", secondary: "+230" },
  MX: { primary: "Mexico", secondary: "+52" },
  FM: { primary: "Micronesia, Federated States of", secondary: "+691" },
  MD: { primary: "Republic of Moldova", secondary: "+373" },
  MC: { primary: "Monaco", secondary: "+377" },
  MN: { primary: "Mongolia", secondary: "+976" },
  ME: { primary: "Montenegro", secondary: "+382" },
  MS: { primary: "Montserrat", secondary: "+1 664" },
  MA: { primary: "Morocco", secondary: "+212" },
  MZ: { primary: "Mozambique", secondary: "+258" },
  MM: { primary: "Myanmar", secondary: "+95" },
  NA: { primary: "Namibia", secondary: "+264" },
  NR: { primary: "Nauru", secondary: "+674" },
  NP: { primary: "Nepal", secondary: "+977" },
  NL: { primary: "Netherlands", secondary: "+31" },
  NZ: { primary: "New Zealand", secondary: "+64" },
  NI: { primary: "Nicaragua", secondary: "+505" },
  NE: { primary: "Niger", secondary: "+227" },
  NG: { primary: "Nigeria", secondary: "+234" },
  NU: { primary: "Niue", secondary: "+683" },
  NF: { primary: "Norfolk Island", secondary: "+672" },
  MP: { primary: "Northern Mariana Islands", secondary: "+1 670" },
  NO: { primary: "Norway", secondary: "+47" },
  OM: { primary: "Oman", secondary: "+968" },
  PK: { primary: "Pakistan", secondary: "+92" },
  PW: { primary: "Palau", secondary: "+680" },
  PS: { primary: "Palestinian Territory", secondary: "+970" },
  PA: { primary: "Panama", secondary: "+507" },
  PG: { primary: "Papua New Guinea", secondary: "+675" },
  PY: { primary: "Paraguay", secondary: "+595" },
  PE: { primary: "Peru", secondary: "+51" },
  PH: { primary: "Philippines", secondary: "+63" },
  PN: { primary: "Pitcairn", secondary: "+872" },
  PL: { primary: "Poland", secondary: "+48" },
  PT: { primary: "Portugal", secondary: "+351" },
  PR: { primary: "Puerto Rico", secondary: "+1 787" },
  QA: { primary: "Qatar", secondary: "+974" },
  RO: { primary: "Romania", secondary: "+40" },
  RU: { primary: "Russia", secondary: "+7" },
  RW: { primary: "Rwanda", secondary: "+250" },
  KN: { primary: "Saint Kitts and Nevis", secondary: "+1 869" },
  LC: { primary: "Saint Lucia", secondary: "+1 758" },
  WS: { primary: "Samoa", secondary: "+685" },
  SM: { primary: "San Marino", secondary: "+378" },
  ST: { primary: "Sao Tome and Principe", secondary: "+239" },
  SA: { primary: "Saudi Arabia", secondary: "+966" },
  SN: { primary: "Senegal", secondary: "+221" },
  RS: { primary: "Serbia", secondary: "+381" },
  SC: { primary: "Seychelles", secondary: "+248" },
  SL: { primary: "Sierra Leone", secondary: "+232" },
  SG: { primary: "Singapore", secondary: "+65" },
  SX: { primary: "Sint Maarten", secondary: "+1 721" },
  SK: { primary: "Slovakia", secondary: "+421" },
  SI: { primary: "Slovenia", secondary: "+386" },
  SB: { primary: "Solomon Islands", secondary: "+677" },
  SO: { primary: "Somalia", secondary: "+252" },
  ZA: { primary: "South Africa", secondary: "+27" },
  SS: { primary: "South Sudan", secondary: "+211" },
  ES: { primary: "Spain", secondary: "+34" },
  LK: { primary: "Sri Lanka", secondary: "+94" },
  SD: { primary: "Sudan", secondary: "+249" },
  SR: { primary: "Suriname", secondary: "+597" },
  SZ: { primary: "Swaziland", secondary: "+268" },
  SE: { primary: "Sweden", secondary: "+46" },
  CH: { primary: "Switzerland", secondary: "+41" },
  SY: { primary: "Syria", secondary: "+963" },
  TW: { primary: "Taiwan", secondary: "+886" },
  TJ: { primary: "Tajikistan", secondary: "+992" },
  TZ: { primary: "Tanzania", secondary: "+255" },
  TH: { primary: "Thailand", secondary: "+66" },
  TG: { primary: "Togo", secondary: "+228" },
  TK: { primary: "Tokelau", secondary: "+690" },
  TO: { primary: "Tonga", secondary: "+676" },
  TT: { primary: "Trinidad and Tobago", secondary: "+1 868" },
  TN: { primary: "Tunisia", secondary: "+216" },
  TR: { primary: "Turkey", secondary: "+90" },
  TM: { primary: "Turkmenistan", secondary: "+993" },
  TC: { primary: "Turks and Caicos Islands", secondary: "+1 649" },
  TV: { primary: "Tuvalu", secondary: "+688" },
  UG: { primary: "Uganda", secondary: "+256" },
  UA: { primary: "Ukraine", secondary: "+380" },
  AE: { primary: "United Arab Emirates", secondary: "+971" },
  GB: { primary: "United Kingdom", secondary: "+44" },
  US: { primary: "United States", secondary: "+1" },
  UY: { primary: "Uruguay", secondary: "+598" },
  UZ: { primary: "Uzbekistan", secondary: "+998" },
  VU: { primary: "Vanuatu", secondary: "+678" },
  VE: { primary: "Venezuela, Bolivarian Republic of", secondary: "+58" },
  VN: { primary: "Viet Nam", secondary: "+84" },
  VI: { primary: "Virgin Islands", secondary: "+1 340" },
  YE: { primary: "Yemen", secondary: "+967" },
  ZM: { primary: "Zambia", secondary: "+260" },
  ZW: { primary: "Zimbabwe", secondary: "+263" },
};

export const countries = [
  {
    alpha2: "AD",
    alpha3: "AND",
    countryCallingCodes: ["+376"],
    currencies: ["EUR"],
    emoji: "🇦🇩",
    ioc: "AND",
    languages: ["cat"],
    title: "Andorra",
    value: "Andorra",
    status: "assigned",
  },
  {
    alpha2: "AE",
    alpha3: "ARE",
    countryCallingCodes: ["+971"],
    currencies: ["AED"],
    emoji: "🇦🇪",
    ioc: "UAE",
    languages: ["ara"],
    title: "United Arab Emirates",
    value: "United Arab Emirates",
    status: "assigned",
  },
  {
    alpha2: "AF",
    alpha3: "AFG",
    countryCallingCodes: ["+93"],
    currencies: ["AFN"],
    emoji: "🇦🇫",
    ioc: "AFG",
    languages: ["pus"],
    title: "Afghanistan",
    value: "Afghanistan",
    status: "assigned",
  },
  {
    alpha2: "AG",
    alpha3: "ATG",
    countryCallingCodes: ["+1 268"],
    currencies: ["XCD"],
    emoji: "🇦🇬",
    ioc: "ANT",
    languages: ["eng"],
    title: "Antigua And Barbuda",
    value: "Antigua And Barbuda",
    status: "assigned",
  },
  {
    alpha2: "AI",
    alpha3: "AIA",
    countryCallingCodes: ["+1 264"],
    currencies: ["XCD"],
    emoji: "🇦🇮",
    ioc: "",
    languages: ["eng"],
    title: "Anguilla",
    value: "Anguilla",
    status: "assigned",
  },

  {
    alpha2: "AL",
    alpha3: "ALB",
    countryCallingCodes: ["+355"],
    currencies: ["ALL"],
    emoji: "🇦🇱",
    ioc: "ALB",
    languages: ["sqi"],
    title: "Albania",
    value: "Albania",
    status: "assigned",
  },
  {
    alpha2: "AM",
    alpha3: "ARM",
    countryCallingCodes: ["+374"],
    currencies: ["AMD"],
    emoji: "🇦🇲",
    ioc: "ARM",
    languages: ["hye", "rus"],
    title: "Armenia",
    value: "Armenia",
    status: "assigned",
  },

  {
    alpha2: "AO",
    alpha3: "AGO",
    countryCallingCodes: ["+244"],
    currencies: ["AOA"],
    emoji: "🇦🇴",
    ioc: "ANG",
    languages: ["por"],
    title: "Angola",
    value: "Angola",
    status: "assigned",
  },
  {
    alpha2: "AQ",
    alpha3: "ATA",
    countryCallingCodes: ["+672"],
    currencies: [],
    emoji: "🇦🇶",
    ioc: "",
    languages: [],
    title: "Antarctica",
    value: "Antarctica",
    status: "assigned",
  },
  {
    alpha2: "AR",
    alpha3: "ARG",
    countryCallingCodes: ["+54"],
    currencies: ["ARS"],
    emoji: "🇦🇷",
    ioc: "ARG",
    languages: ["spa"],
    title: "Argentina",
    value: "Argentina",
    status: "assigned",
  },
  {
    alpha2: "AS",
    alpha3: "ASM",
    countryCallingCodes: ["+1 684"],
    currencies: ["USD"],
    emoji: "🇦🇸",
    ioc: "ASA",
    languages: ["eng", "smo"],
    title: "American Samoa",
    value: "American Samoa",
    status: "assigned",
  },
  {
    alpha2: "AT",
    alpha3: "AUT",
    countryCallingCodes: ["+43"],
    currencies: ["EUR"],
    emoji: "🇦🇹",
    ioc: "AUT",
    languages: ["deu"],
    title: "Austria",
    value: "Austria",
    status: "assigned",
  },
  {
    alpha2: "AU",
    alpha3: "AUS",
    countryCallingCodes: ["+61"],
    currencies: ["AUD"],
    emoji: "🇦🇺",
    ioc: "AUS",
    languages: ["eng"],
    title: "Australia",
    value: "Australia",
    status: "assigned",
  },
  {
    alpha2: "AW",
    alpha3: "ABW",
    countryCallingCodes: ["+297"],
    currencies: ["AWG"],
    emoji: "🇦🇼",
    ioc: "ARU",
    languages: ["nld"],
    title: "Aruba",
    value: "Aruba",
    status: "assigned",
  },
  {
    alpha2: "AX",
    alpha3: "ALA",
    countryCallingCodes: ["+358"],
    currencies: ["EUR"],
    emoji: "🇦🇽",
    ioc: "",
    languages: ["swe"],
    title: "Åland Islands",
    value: "Åland Islands",
    status: "assigned",
  },
  {
    alpha2: "AZ",
    alpha3: "AZE",
    countryCallingCodes: ["+994"],
    currencies: ["AZN"],
    emoji: "🇦🇿",
    ioc: "AZE",
    languages: ["aze"],
    title: "Azerbaijan",
    value: "Azerbaijan",
    status: "assigned",
  },
  {
    alpha2: "BA",
    alpha3: "BIH",
    countryCallingCodes: ["+387"],
    currencies: ["BAM"],
    emoji: "🇧🇦",
    ioc: "BIH",
    languages: ["bos", "cre", "srp"],
    title: "Bosnia & Herzegovina",
    value: "Bosnia & Herzegovina",
    status: "assigned",
  },
  {
    alpha2: "BB",
    alpha3: "BRB",
    countryCallingCodes: ["+1 246"],
    currencies: ["BBD"],
    emoji: "🇧🇧",
    ioc: "BAR",
    languages: ["eng"],
    title: "Barbados",
    value: "Barbados",
    status: "assigned",
  },
  {
    alpha2: "BD",
    alpha3: "BGD",
    countryCallingCodes: ["+880"],
    currencies: ["BDT"],
    emoji: "🇧🇩",
    ioc: "BAN",
    languages: ["ben"],
    title: "Bangladesh",
    value: "Bangladesh",
    status: "assigned",
  },
  {
    alpha2: "BE",
    alpha3: "BEL",
    countryCallingCodes: ["+32"],
    currencies: ["EUR"],
    emoji: "🇧🇪",
    ioc: "BEL",
    languages: ["nld", "fra", "deu"],
    title: "Belgium",
    value: "Belgium",
    status: "assigned",
  },
  {
    alpha2: "BF",
    alpha3: "BFA",
    countryCallingCodes: ["+226"],
    currencies: ["XOF"],
    emoji: "🇧🇫",
    ioc: "BUR",
    languages: ["fra"],
    title: "Burkina Faso",
    value: "Burkina Faso",
    status: "assigned",
  },
  {
    alpha2: "BG",
    alpha3: "BGR",
    countryCallingCodes: ["+359"],
    currencies: ["BGN"],
    emoji: "🇧🇬",
    ioc: "BUL",
    languages: ["bul"],
    title: "Bulgaria",
    value: "Bulgaria",
    status: "assigned",
  },
  {
    alpha2: "BH",
    alpha3: "BHR",
    countryCallingCodes: ["+973"],
    currencies: ["BHD"],
    emoji: "🇧🇭",
    ioc: "BRN",
    languages: ["ara"],
    title: "Bahrain",
    value: "Bahrain",
    status: "assigned",
  },
  {
    alpha2: "BI",
    alpha3: "BDI",
    countryCallingCodes: ["+257"],
    currencies: ["BIF"],
    emoji: "🇧🇮",
    ioc: "BDI",
    languages: ["fra"],
    title: "Burundi",
    value: "Burundi",
    status: "assigned",
  },
  {
    alpha2: "BJ",
    alpha3: "BEN",
    countryCallingCodes: ["+229"],
    currencies: ["XOF"],
    emoji: "🇧🇯",
    ioc: "BEN",
    languages: ["fra"],
    title: "Benin",
    value: "Benin",
    status: "assigned",
  },
  {
    alpha2: "BL",
    alpha3: "BLM",
    countryCallingCodes: ["+590"],
    currencies: ["EUR"],
    emoji: "🇧🇱",
    ioc: "",
    languages: ["fra"],
    title: "Saint Barthélemy",
    value: "Saint Barthélemy",
    status: "assigned",
  },
  {
    alpha2: "BM",
    alpha3: "BMU",
    countryCallingCodes: ["+1 441"],
    currencies: ["BMD"],
    emoji: "🇧🇲",
    ioc: "BER",
    languages: ["eng"],
    title: "Bermuda",
    value: "Bermuda",
    status: "assigned",
  },
  {
    alpha2: "BN",
    alpha3: "BRN",
    countryCallingCodes: ["+673"],
    currencies: ["BND"],
    emoji: "🇧🇳",
    ioc: "BRU",
    languages: ["msa", "eng"],
    title: "Brunei Darussalam",
    value: "Brunei Darussalam",
    status: "assigned",
  },
  {
    alpha2: "BO",
    alpha3: "BOL",
    countryCallingCodes: ["+591"],
    currencies: ["BOB", "BOV"],
    emoji: "🇧🇴",
    ioc: "BOL",
    languages: ["spa", "aym", "que"],
    title: "Bolivia, Plurinational State Of",
    value: "Bolivia, Plurinational State Of",
    status: "assigned",
  },
  {
    alpha2: "BQ",
    alpha3: "BES",
    countryCallingCodes: ["+599"],
    currencies: ["USD"],
    emoji: "🇧🇶",
    ioc: "",
    languages: ["nld"],
    title: "Bonaire, Sint Eustatius And Saba",
    value: "Bonaire, Sint Eustatius And Saba",
    status: "assigned",
  },

  {
    alpha2: "BR",
    alpha3: "BRA",
    countryCallingCodes: ["+55"],
    currencies: ["BRL"],
    emoji: "🇧🇷",
    ioc: "BRA",
    languages: ["por"],
    title: "Brazil",
    value: "Brazil",
    status: "assigned",
  },
  {
    alpha2: "BS",
    alpha3: "BHS",
    countryCallingCodes: ["+1 242"],
    currencies: ["BSD"],
    emoji: "🇧🇸",
    ioc: "BAH",
    languages: ["eng"],
    title: "Bahamas",
    value: "Bahamas",
    status: "assigned",
  },
  {
    alpha2: "BT",
    alpha3: "BTN",
    countryCallingCodes: ["+975"],
    currencies: ["INR", "BTN"],
    emoji: "🇧🇹",
    ioc: "BHU",
    languages: ["dzo"],
    title: "Bhutan",
    value: "Bhutan",
    status: "assigned",
  },
  {
    alpha2: "BU",
    alpha3: "BUR",
    countryCallingCodes: [],
    currencies: [],
    ioc: "",
    languages: [],
    title: "Burma",
    value: "Burma",
    status: "deleted",
  },
  {
    alpha2: "BV",
    alpha3: "BVT",
    countryCallingCodes: [],
    currencies: ["NOK"],
    emoji: "🇧🇻",
    ioc: "",
    languages: [],
    title: "Bouvet Island",
    value: "Bouvet Island",
    status: "assigned",
  },
  {
    alpha2: "BW",
    alpha3: "BWA",
    countryCallingCodes: ["+267"],
    currencies: ["BWP"],
    emoji: "🇧🇼",
    ioc: "BOT",
    languages: ["eng", "tsn"],
    title: "Botswana",
    value: "Botswana",
    status: "assigned",
  },
  {
    alpha2: "BY",
    alpha3: "BLR",
    countryCallingCodes: ["+375"],
    currencies: ["BYN"],
    emoji: "🇧🇾",
    ioc: "BLR",
    languages: ["bel", "rus"],
    title: "Belarus",
    value: "Belarus",
    status: "assigned",
  },
  {
    alpha2: "BZ",
    alpha3: "BLZ",
    countryCallingCodes: ["+501"],
    currencies: ["BZD"],
    emoji: "🇧🇿",
    ioc: "BIZ",
    languages: ["eng"],
    title: "Belize",
    value: "Belize",
    status: "assigned",
  },
  {
    alpha2: "CA",
    alpha3: "CAN",
    countryCallingCodes: ["+1"],
    currencies: ["CAD"],
    emoji: "🇨🇦",
    ioc: "CAN",
    languages: ["eng", "fra"],
    title: "Canada",
    value: "Canada",
    status: "assigned",
  },
  {
    alpha2: "CC",
    alpha3: "CCK",
    countryCallingCodes: ["+61"],
    currencies: ["AUD"],
    emoji: "🇨🇨",
    ioc: "",
    languages: ["eng"],
    title: "Cocos (Keeling) Islands",
    value: "Cocos (Keeling) Islands",
    status: "assigned",
  },
  {
    alpha2: "CD",
    alpha3: "COD",
    countryCallingCodes: ["+243"],
    currencies: ["CDF"],
    emoji: "🇨🇩",
    ioc: "COD",
    languages: ["fra", "lin", "kon", "swa"],
    title: "Democratic Republic Of Congo",
    value: "Democratic Republic Of Congo",
    status: "assigned",
  },
  {
    alpha2: "CF",
    alpha3: "CAF",
    countryCallingCodes: ["+236"],
    currencies: ["XAF"],
    emoji: "🇨🇫",
    ioc: "CAF",
    languages: ["fra", "sag"],
    title: "Central African Republic",
    value: "Central African Republic",
    status: "assigned",
  },
  {
    alpha2: "CG",
    alpha3: "COG",
    countryCallingCodes: ["+242"],
    currencies: ["XAF"],
    emoji: "🇨🇬",
    ioc: "CGO",
    languages: ["fra", "lin"],
    title: "Republic Of Congo",
    value: "Republic Of Congo",
    status: "assigned",
  },
  {
    alpha2: "CH",
    alpha3: "CHE",
    countryCallingCodes: ["+41"],
    currencies: ["CHF", "CHE", "CHW"],
    emoji: "🇨🇭",
    ioc: "SUI",
    languages: ["deu", "fra", "ita", "roh"],
    title: "Switzerland",
    value: "Switzerland",
    status: "assigned",
  },
  {
    alpha2: "CI",
    alpha3: "CIV",
    countryCallingCodes: ["+225"],
    currencies: ["XOF"],
    emoji: "🇨🇮",
    ioc: "CIV",
    languages: ["fra"],
    title: "Côte d'Ivoire",
    value: "Côte d'Ivoire",
    status: "assigned",
  },
  {
    alpha2: "CK",
    alpha3: "COK",
    countryCallingCodes: ["+682"],
    currencies: ["NZD"],
    emoji: "🇨🇰",
    ioc: "COK",
    languages: ["eng", "mri"],
    title: "Cook Islands",
    value: "Cook Islands",
    status: "assigned",
  },
  {
    alpha2: "CL",
    alpha3: "CHL",
    countryCallingCodes: ["+56"],
    currencies: ["CLP", "CLF"],
    emoji: "🇨🇱",
    ioc: "CHI",
    languages: ["spa"],
    title: "Chile",
    value: "Chile",
    status: "assigned",
  },
  {
    alpha2: "CM",
    alpha3: "CMR",
    countryCallingCodes: ["+237"],
    currencies: ["XAF"],
    emoji: "🇨🇲",
    ioc: "CMR",
    languages: ["eng", "fra"],
    title: "Cameroon",
    value: "Cameroon",
    status: "assigned",
  },
  {
    alpha2: "CN",
    alpha3: "CHN",
    countryCallingCodes: ["+86"],
    currencies: ["CNY"],
    emoji: "🇨🇳",
    ioc: "CHN",
    languages: ["zho"],
    title: "China",
    value: "China",
    status: "assigned",
  },
  {
    alpha2: "CO",
    alpha3: "COL",
    countryCallingCodes: ["+57"],
    currencies: ["COP", "COU"],
    emoji: "🇨🇴",
    ioc: "COL",
    languages: ["spa"],
    title: "Colombia",
    value: "Colombia",
    status: "assigned",
  },

  {
    alpha2: "CR",
    alpha3: "CRI",
    countryCallingCodes: ["+506"],
    currencies: ["CRC"],
    emoji: "🇨🇷",
    ioc: "CRC",
    languages: ["spa"],
    title: "Costa Rica",
    value: "Costa Rica",
    status: "assigned",
  },
  {
    alpha2: "CU",
    alpha3: "CUB",
    countryCallingCodes: ["+53"],
    currencies: ["CUP", "CUC"],
    emoji: "🇨🇺",
    ioc: "CUB",
    languages: ["spa"],
    title: "Cuba",
    value: "Cuba",
    status: "assigned",
  },
  {
    alpha2: "CV",
    alpha3: "CPV",
    countryCallingCodes: ["+238"],
    currencies: ["CVE"],
    emoji: "🇨🇻",
    ioc: "CPV",
    languages: ["por"],
    title: "Cabo Verde",
    value: "Cabo Verde",
    status: "assigned",
  },
  {
    alpha2: "CW",
    alpha3: "CUW",
    countryCallingCodes: ["+599"],
    currencies: ["ANG"],
    emoji: "🇨🇼",
    ioc: "",
    languages: ["nld"],
    title: "Curacao",
    value: "Curacao",
    status: "assigned",
  },
  {
    alpha2: "CX",
    alpha3: "CXR",
    countryCallingCodes: ["+61"],
    currencies: ["AUD"],
    emoji: "🇨🇽",
    ioc: "",
    languages: ["eng"],
    title: "Christmas Island",
    value: "Christmas Island",
    status: "assigned",
  },
  {
    alpha2: "CY",
    alpha3: "CYP",
    countryCallingCodes: ["+357"],
    currencies: ["EUR"],
    emoji: "🇨🇾",
    ioc: "CYP",
    languages: ["ell", "tur"],
    title: "Cyprus",
    value: "Cyprus",
    status: "assigned",
  },
  {
    alpha2: "CZ",
    alpha3: "CZE",
    countryCallingCodes: ["+420"],
    currencies: ["CZK"],
    emoji: "🇨🇿",
    ioc: "CZE",
    languages: ["ces"],
    title: "Czech Republic",
    value: "Czech Republic",
    status: "assigned",
  },
  {
    alpha2: "DE",
    alpha3: "DEU",
    countryCallingCodes: ["+49"],
    currencies: ["EUR"],
    emoji: "🇩🇪",
    ioc: "GER",
    languages: ["deu"],
    title: "Germany",
    value: "Germany",
    status: "assigned",
  },

  {
    alpha2: "DJ",
    alpha3: "DJI",
    countryCallingCodes: ["+253"],
    currencies: ["DJF"],
    emoji: "🇩🇯",
    ioc: "DJI",
    languages: ["ara", "fra"],
    title: "Djibouti",
    value: "Djibouti",
    status: "assigned",
  },
  {
    alpha2: "DK",
    alpha3: "DNK",
    countryCallingCodes: ["+45"],
    currencies: ["DKK"],
    emoji: "🇩🇰",
    ioc: "DEN",
    languages: ["dan"],
    title: "Denmark",
    value: "Denmark",
    status: "assigned",
  },
  {
    alpha2: "DM",
    alpha3: "DMA",
    countryCallingCodes: ["+1 767"],
    currencies: ["XCD"],
    emoji: "🇩🇲",
    ioc: "DMA",
    languages: ["eng"],
    title: "Dominica",
    value: "Dominica",
    status: "assigned",
  },
  {
    alpha2: "DO",
    alpha3: "DOM",
    countryCallingCodes: ["+1 809", "+1 829", "+1 849"],
    currencies: ["DOP"],
    emoji: "🇩🇴",
    ioc: "DOM",
    languages: ["spa"],
    title: "Dominican Republic",
    value: "Dominican Republic",
    status: "assigned",
  },

  {
    alpha2: "DZ",
    alpha3: "DZA",
    countryCallingCodes: ["+213"],
    currencies: ["DZD"],
    emoji: "🇩🇿",
    ioc: "ALG",
    languages: ["ara"],
    title: "Algeria",
    value: "Algeria",
    status: "assigned",
  },

  {
    alpha2: "EC",
    alpha3: "ECU",
    countryCallingCodes: ["+593"],
    currencies: ["USD"],
    emoji: "🇪🇨",
    ioc: "ECU",
    languages: ["spa", "que"],
    title: "Ecuador",
    value: "Ecuador",
    status: "assigned",
  },
  {
    alpha2: "EE",
    alpha3: "EST",
    countryCallingCodes: ["+372"],
    currencies: ["EUR"],
    emoji: "🇪🇪",
    ioc: "EST",
    languages: ["est"],
    title: "Estonia",
    value: "Estonia",
    status: "assigned",
  },
  {
    alpha2: "EG",
    alpha3: "EGY",
    countryCallingCodes: ["+20"],
    currencies: ["EGP"],
    emoji: "🇪🇬",
    ioc: "EGY",
    languages: ["ara"],
    title: "Egypt",
    value: "Egypt",
    status: "assigned",
  },
  {
    alpha2: "EH",
    alpha3: "ESH",
    countryCallingCodes: ["+212"],
    currencies: ["MAD"],
    emoji: "🇪🇭",
    ioc: "",
    languages: [],
    title: "Western Sahara",
    value: "Western Sahara",
    status: "assigned",
  },
  {
    alpha2: "ER",
    alpha3: "ERI",
    countryCallingCodes: ["+291"],
    currencies: ["ERN"],
    emoji: "🇪🇷",
    ioc: "ERI",
    languages: ["eng", "ara", "tir"],
    title: "Eritrea",
    value: "Eritrea",
    status: "assigned",
  },
  {
    alpha2: "ES",
    alpha3: "ESP",
    countryCallingCodes: ["+34"],
    currencies: ["EUR"],
    emoji: "🇪🇸",
    ioc: "ESP",
    languages: ["spa", "cat", "glg", "eus"],
    title: "Spain",
    value: "Spain",
    status: "assigned",
  },
  {
    alpha2: "ET",
    alpha3: "ETH",
    countryCallingCodes: ["+251"],
    currencies: ["ETB"],
    emoji: "🇪🇹",
    ioc: "ETH",
    languages: ["amh"],
    title: "Ethiopia",
    value: "Ethiopia",
    status: "assigned",
  },
  {
    alpha2: "EU",
    alpha3: "",
    countryCallingCodes: ["+388"],
    currencies: ["EUR"],
    emoji: "🇪🇺",
    ioc: "",
    languages: [],
    title: "European Union",
    value: "European Union",
    status: "reserved",
  },
  {
    alpha2: "FI",
    alpha3: "FIN",
    countryCallingCodes: ["+358"],
    currencies: ["EUR"],
    emoji: "🇫🇮",
    ioc: "FIN",
    languages: ["fin", "swe"],
    title: "Finland",
    value: "Finland",
    status: "assigned",
  },
  {
    alpha2: "FJ",
    alpha3: "FJI",
    countryCallingCodes: ["+679"],
    currencies: ["FJD"],
    emoji: "🇫🇯",
    ioc: "FIJ",
    languages: ["eng", "fij"],
    title: "Fiji",
    value: "Fiji",
    status: "assigned",
  },
  {
    alpha2: "FK",
    alpha3: "FLK",
    countryCallingCodes: ["+500"],
    currencies: ["FKP"],
    emoji: "🇫🇰",
    ioc: "",
    languages: ["eng"],
    title: "Falkland Islands",
    value: "Falkland Islands",
    status: "assigned",
  },
  {
    alpha2: "FM",
    alpha3: "FSM",
    countryCallingCodes: ["+691"],
    currencies: ["USD"],
    emoji: "🇫🇲",
    ioc: "FSM",
    languages: ["eng"],
    title: "Micronesia, Federated States Of",
    value: "Micronesia, Federated States Of",
    status: "assigned",
  },
  {
    alpha2: "FO",
    alpha3: "FRO",
    countryCallingCodes: ["+298"],
    currencies: ["DKK"],
    emoji: "🇫🇴",
    ioc: "FAI",
    languages: ["fao", "dan"],
    title: "Faroe Islands",
    value: "Faroe Islands",
    status: "assigned",
  },

  {
    alpha2: "FR",
    alpha3: "FRA",
    countryCallingCodes: ["+33"],
    currencies: ["EUR"],
    emoji: "🇫🇷",
    ioc: "FRA",
    languages: ["fra"],
    title: "France",
    value: "France",
    status: "assigned",
  },

  {
    alpha2: "GA",
    alpha3: "GAB",
    countryCallingCodes: ["+241"],
    currencies: ["XAF"],
    emoji: "🇬🇦",
    ioc: "GAB",
    languages: ["fra"],
    title: "Gabon",
    value: "Gabon",
    status: "assigned",
  },
  {
    alpha2: "GB",
    alpha3: "GBR",
    countryCallingCodes: ["+44"],
    currencies: ["GBP"],
    emoji: "🇬🇧",
    ioc: "GBR",
    languages: ["eng", "cor", "gle", "gla", "cym"],
    title: "United Kingdom",
    value: "United Kingdom",
    status: "assigned",
  },
  {
    alpha2: "GD",
    alpha3: "GRD",
    countryCallingCodes: ["+473"],
    currencies: ["XCD"],
    emoji: "🇬🇩",
    ioc: "GRN",
    languages: ["eng"],
    title: "Grenada",
    value: "Grenada",
    status: "assigned",
  },
  {
    alpha2: "GE",
    alpha3: "GEO",
    countryCallingCodes: ["+995"],
    currencies: ["GEL"],
    emoji: "🇬🇪",
    ioc: "GEO",
    languages: ["kat"],
    title: "Georgia",
    value: "Georgia",
    status: "assigned",
  },
  {
    alpha2: "GF",
    alpha3: "GUF",
    countryCallingCodes: ["+594"],
    currencies: ["EUR"],
    emoji: "🇬🇫",
    ioc: "",
    languages: ["fra"],
    title: "French Guiana",
    value: "French Guiana",
    status: "assigned",
  },
  {
    alpha2: "GG",
    alpha3: "GGY",
    countryCallingCodes: ["+44"],
    currencies: ["GBP"],
    emoji: "🇬🇬",
    ioc: "GCI",
    languages: ["fra"],
    title: "Guernsey",
    value: "Guernsey",
    status: "assigned",
  },
  {
    alpha2: "GH",
    alpha3: "GHA",
    countryCallingCodes: ["+233"],
    currencies: ["GHS"],
    emoji: "🇬🇭",
    ioc: "GHA",
    languages: ["eng"],
    title: "Ghana",
    value: "Ghana",
    status: "assigned",
  },
  {
    alpha2: "GI",
    alpha3: "GIB",
    countryCallingCodes: ["+350"],
    currencies: ["GIP"],
    emoji: "🇬🇮",
    ioc: "",
    languages: ["eng"],
    title: "Gibraltar",
    value: "Gibraltar",
    status: "assigned",
  },
  {
    alpha2: "GL",
    alpha3: "GRL",
    countryCallingCodes: ["+299"],
    currencies: ["DKK"],
    emoji: "🇬🇱",
    ioc: "",
    languages: ["kal"],
    title: "Greenland",
    value: "Greenland",
    status: "assigned",
  },
  {
    alpha2: "GM",
    alpha3: "GMB",
    countryCallingCodes: ["+220"],
    currencies: ["GMD"],
    emoji: "🇬🇲",
    ioc: "GAM",
    languages: ["eng"],
    title: "Gambia",
    value: "Gambia",
    status: "assigned",
  },
  {
    alpha2: "GN",
    alpha3: "GIN",
    countryCallingCodes: ["+224"],
    currencies: ["GNF"],
    emoji: "🇬🇳",
    ioc: "GUI",
    languages: ["fra"],
    title: "Guinea",
    value: "Guinea",
    status: "assigned",
  },
  {
    alpha2: "GP",
    alpha3: "GLP",
    countryCallingCodes: ["+590"],
    currencies: ["EUR"],
    emoji: "🇬🇵",
    ioc: "",
    languages: ["fra"],
    title: "Guadeloupe",
    value: "Guadeloupe",
    status: "assigned",
  },
  {
    alpha2: "GQ",
    alpha3: "GNQ",
    countryCallingCodes: ["+240"],
    currencies: ["XAF"],
    emoji: "🇬🇶",
    ioc: "GEQ",
    languages: ["spa", "fra", "por"],
    title: "Equatorial Guinea",
    value: "Equatorial Guinea",
    status: "assigned",
  },
  {
    alpha2: "GR",
    alpha3: "GRC",
    countryCallingCodes: ["+30"],
    currencies: ["EUR"],
    emoji: "🇬🇷",
    ioc: "GRE",
    languages: ["ell"],
    title: "Greece",
    value: "Greece",
    status: "assigned",
  },
  {
    alpha2: "GS",
    alpha3: "SGS",
    countryCallingCodes: ["+500"],
    currencies: ["GBP"],
    emoji: "🇬🇸",
    ioc: "",
    languages: ["eng"],
    title: "South Georgia And The South Sandwich Islands",
    value: "South Georgia And The South Sandwich Islands",
    status: "assigned",
  },
  {
    alpha2: "GT",
    alpha3: "GTM",
    countryCallingCodes: ["+502"],
    currencies: ["GTQ"],
    emoji: "🇬🇹",
    ioc: "GUA",
    languages: ["spa"],
    title: "Guatemala",
    value: "Guatemala",
    status: "assigned",
  },
  {
    alpha2: "GU",
    alpha3: "GUM",
    countryCallingCodes: ["+1 671"],
    currencies: ["USD"],
    emoji: "🇬🇺",
    ioc: "GUM",
    languages: ["eng"],
    title: "Guam",
    value: "Guam",
    status: "assigned",
  },
  {
    alpha2: "GW",
    alpha3: "GNB",
    countryCallingCodes: ["+245"],
    currencies: ["XOF"],
    emoji: "🇬🇼",
    ioc: "GBS",
    languages: ["por"],
    title: "Guinea-bissau",
    value: "Guinea-bissau",
    status: "assigned",
  },
  {
    alpha2: "GY",
    alpha3: "GUY",
    countryCallingCodes: ["+592"],
    currencies: ["GYD"],
    emoji: "🇬🇾",
    ioc: "GUY",
    languages: ["eng"],
    title: "Guyana",
    value: "Guyana",
    status: "assigned",
  },
  {
    alpha2: "HK",
    alpha3: "HKG",
    countryCallingCodes: ["+852"],
    currencies: ["HKD"],
    emoji: "🇭🇰",
    ioc: "HKG",
    languages: ["zho", "eng"],
    title: "Hong Kong",
    value: "Hong Kong",
    status: "assigned",
  },
  {
    alpha2: "HM",
    alpha3: "HMD",
    countryCallingCodes: [],
    currencies: ["AUD"],
    emoji: "🇭🇲",
    ioc: "",
    languages: [],
    title: "Heard Island And McDonald Islands",
    value: "Heard Island And McDonald Islands",
    status: "assigned",
  },
  {
    alpha2: "HN",
    alpha3: "HND",
    countryCallingCodes: ["+504"],
    currencies: ["HNL"],
    emoji: "🇭🇳",
    ioc: "HON",
    languages: ["spa"],
    title: "Honduras",
    value: "Honduras",
    status: "assigned",
  },
  {
    alpha2: "HR",
    alpha3: "HRV",
    countryCallingCodes: ["+385"],
    currencies: ["EUR"],
    emoji: "🇭🇷",
    ioc: "CRO",
    languages: ["hrv"],
    title: "Croatia",
    value: "Croatia",
    status: "assigned",
  },
  {
    alpha2: "HT",
    alpha3: "HTI",
    countryCallingCodes: ["+509"],
    currencies: ["HTG", "USD"],
    emoji: "🇭🇹",
    ioc: "HAI",
    languages: ["fra", "hat"],
    title: "Haiti",
    value: "Haiti",
    status: "assigned",
  },
  {
    alpha2: "HU",
    alpha3: "HUN",
    countryCallingCodes: ["+36"],
    currencies: ["HUF"],
    emoji: "🇭🇺",
    ioc: "HUN",
    languages: ["hun"],
    title: "Hungary",
    value: "Hungary",
    status: "assigned",
  },

  {
    alpha2: "ID",
    alpha3: "IDN",
    countryCallingCodes: ["+62"],
    currencies: ["IDR"],
    emoji: "🇮🇩",
    ioc: "INA",
    languages: ["ind"],
    title: "Indonesia",
    value: "Indonesia",
    status: "assigned",
  },
  {
    alpha2: "IE",
    alpha3: "IRL",
    countryCallingCodes: ["+353"],
    currencies: ["EUR"],
    emoji: "🇮🇪",
    ioc: "IRL",
    languages: ["eng", "gle"],
    title: "Ireland",
    value: "Ireland",
    status: "assigned",
  },
  {
    alpha2: "IL",
    alpha3: "ISR",
    countryCallingCodes: ["+972"],
    currencies: ["ILS"],
    emoji: "🇮🇱",
    ioc: "ISR",
    languages: ["heb", "ara", "eng"],
    title: "Israel",
    value: "Israel",
    status: "assigned",
  },
  {
    alpha2: "IM",
    alpha3: "IMN",
    countryCallingCodes: ["+44"],
    currencies: ["GBP"],
    emoji: "🇮🇲",
    ioc: "",
    languages: ["eng", "glv"],
    title: "Isle Of Man",
    value: "Isle Of Man",
    status: "assigned",
  },
  {
    alpha2: "IN",
    alpha3: "IND",
    countryCallingCodes: ["+91"],
    currencies: ["INR"],
    emoji: "🇮🇳",
    ioc: "IND",
    languages: ["eng", "hin"],
    title: "India",
    value: "India",
    status: "assigned",
  },
  {
    alpha2: "IO",
    alpha3: "IOT",
    countryCallingCodes: ["+246"],
    currencies: ["USD"],
    emoji: "🇮🇴",
    ioc: "",
    languages: ["eng"],
    title: "British Indian Ocean Territory",
    value: "British Indian Ocean Territory",
    status: "assigned",
  },
  {
    alpha2: "IQ",
    alpha3: "IRQ",
    countryCallingCodes: ["+964"],
    currencies: ["IQD"],
    emoji: "🇮🇶",
    ioc: "IRQ",
    languages: ["ara", "kur"],
    title: "Iraq",
    value: "Iraq",
    status: "assigned",
  },
  {
    alpha2: "IR",
    alpha3: "IRN",
    countryCallingCodes: ["+98"],
    currencies: ["IRR"],
    emoji: "🇮🇷",
    ioc: "IRI",
    languages: ["fas"],
    title: "Iran, Islamic Republic Of",
    value: "Iran, Islamic Republic Of",
    status: "assigned",
  },
  {
    alpha2: "IS",
    alpha3: "ISL",
    countryCallingCodes: ["+354"],
    currencies: ["ISK"],
    emoji: "🇮🇸",
    ioc: "ISL",
    languages: ["isl"],
    title: "Iceland",
    value: "Iceland",
    status: "assigned",
  },
  {
    alpha2: "IT",
    alpha3: "ITA",
    countryCallingCodes: ["+39"],
    currencies: ["EUR"],
    emoji: "🇮🇹",
    ioc: "ITA",
    languages: ["ita"],
    title: "Italy",
    value: "Italy",
    status: "assigned",
  },
  {
    alpha2: "JE",
    alpha3: "JEY",
    countryCallingCodes: ["+44"],
    currencies: ["GBP"],
    emoji: "🇯🇪",
    ioc: "JCI",
    languages: ["eng", "fra"],
    title: "Jersey",
    value: "Jersey",
    status: "assigned",
  },
  {
    alpha2: "JM",
    alpha3: "JAM",
    countryCallingCodes: ["+1 876"],
    currencies: ["JMD"],
    emoji: "🇯🇲",
    ioc: "JAM",
    languages: ["eng"],
    title: "Jamaica",
    value: "Jamaica",
    status: "assigned",
  },
  {
    alpha2: "JO",
    alpha3: "JOR",
    countryCallingCodes: ["+962"],
    currencies: ["JOD"],
    emoji: "🇯🇴",
    ioc: "JOR",
    languages: ["ara"],
    title: "Jordan",
    value: "Jordan",
    status: "assigned",
  },
  {
    alpha2: "JP",
    alpha3: "JPN",
    countryCallingCodes: ["+81"],
    currencies: ["JPY"],
    emoji: "🇯🇵",
    ioc: "JPN",
    languages: ["jpn"],
    title: "Japan",
    value: "Japan",
    status: "assigned",
  },
  {
    alpha2: "KE",
    alpha3: "KEN",
    countryCallingCodes: ["+254"],
    currencies: ["KES"],
    emoji: "🇰🇪",
    ioc: "KEN",
    languages: ["eng", "swa"],
    title: "Kenya",
    value: "Kenya",
    status: "assigned",
  },
  {
    alpha2: "KG",
    alpha3: "KGZ",
    countryCallingCodes: ["+996"],
    currencies: ["KGS"],
    emoji: "🇰🇬",
    ioc: "KGZ",
    languages: ["rus"],
    title: "Kyrgyzstan",
    value: "Kyrgyzstan",
    status: "assigned",
  },
  {
    alpha2: "KH",
    alpha3: "KHM",
    countryCallingCodes: ["+855"],
    currencies: ["KHR"],
    emoji: "🇰🇭",
    ioc: "CAM",
    languages: ["khm"],
    title: "Cambodia",
    value: "Cambodia",
    status: "assigned",
  },
  {
    alpha2: "KI",
    alpha3: "KIR",
    countryCallingCodes: ["+686"],
    currencies: ["AUD"],
    emoji: "🇰🇮",
    ioc: "KIR",
    languages: ["eng"],
    title: "Kiribati",
    value: "Kiribati",
    status: "assigned",
  },
  {
    alpha2: "KM",
    alpha3: "COM",
    countryCallingCodes: ["+269"],
    currencies: ["KMF"],
    emoji: "🇰🇲",
    ioc: "COM",
    languages: ["ara", "fra"],
    title: "Comoros",
    value: "Comoros",
    status: "assigned",
  },
  {
    alpha2: "KN",
    alpha3: "KNA",
    countryCallingCodes: ["+1 869"],
    currencies: ["XCD"],
    emoji: "🇰🇳",
    ioc: "SKN",
    languages: ["eng"],
    title: "Saint Kitts And Nevis",
    value: "Saint Kitts And Nevis",
    status: "assigned",
  },
  {
    alpha2: "KP",
    alpha3: "PRK",
    countryCallingCodes: ["+850"],
    currencies: ["KPW"],
    emoji: "🇰🇵",
    ioc: "PRK",
    languages: ["kor"],
    title: "Korea, Democratic People's Republic Of",
    value: "Korea, Democratic People's Republic Of",
    status: "assigned",
  },
  {
    alpha2: "KR",
    alpha3: "KOR",
    countryCallingCodes: ["+82"],
    currencies: ["KRW"],
    emoji: "🇰🇷",
    ioc: "KOR",
    languages: ["kor"],
    title: "Korea, Republic Of",
    value: "Korea, Republic Of",
    status: "assigned",
  },
  {
    alpha2: "KW",
    alpha3: "KWT",
    countryCallingCodes: ["+965"],
    currencies: ["KWD"],
    emoji: "🇰🇼",
    ioc: "KUW",
    languages: ["ara"],
    title: "Kuwait",
    value: "Kuwait",
    status: "assigned",
  },
  {
    alpha2: "KY",
    alpha3: "CYM",
    countryCallingCodes: ["+1 345"],
    currencies: ["KYD"],
    emoji: "🇰🇾",
    ioc: "CAY",
    languages: ["eng"],
    title: "Cayman Islands",
    value: "Cayman Islands",
    status: "assigned",
  },
  {
    alpha2: "KZ",
    alpha3: "KAZ",
    countryCallingCodes: ["+7", "+7 6", "+7 7"],
    currencies: ["KZT"],
    emoji: "🇰🇿",
    ioc: "KAZ",
    languages: ["kaz", "rus"],
    title: "Kazakhstan",
    value: "Kazakhstan",
    status: "assigned",
  },
  {
    alpha2: "LA",
    alpha3: "LAO",
    countryCallingCodes: ["+856"],
    currencies: ["LAK"],
    emoji: "🇱🇦",
    ioc: "LAO",
    languages: ["lao"],
    title: "Lao People's Democratic Republic",
    value: "Lao People's Democratic Republic",
    status: "assigned",
  },
  {
    alpha2: "LB",
    alpha3: "LBN",
    countryCallingCodes: ["+961"],
    currencies: ["LBP"],
    emoji: "🇱🇧",
    ioc: "LIB",
    languages: ["ara", "hye"],
    title: "Lebanon",
    value: "Lebanon",
    status: "assigned",
  },
  {
    alpha2: "LC",
    alpha3: "LCA",
    countryCallingCodes: ["+1 758"],
    currencies: ["XCD"],
    emoji: "🇱🇨",
    ioc: "LCA",
    languages: ["eng"],
    title: "Saint Lucia",
    value: "Saint Lucia",
    status: "assigned",
  },
  {
    alpha2: "LI",
    alpha3: "LIE",
    countryCallingCodes: ["+423"],
    currencies: ["CHF"],
    emoji: "🇱🇮",
    ioc: "LIE",
    languages: ["deu"],
    title: "Liechtenstein",
    value: "Liechtenstein",
    status: "assigned",
  },
  {
    alpha2: "LK",
    alpha3: "LKA",
    countryCallingCodes: ["+94"],
    currencies: ["LKR"],
    emoji: "🇱🇰",
    ioc: "SRI",
    languages: ["sin", "tam"],
    title: "Sri Lanka",
    value: "Sri Lanka",
    status: "assigned",
  },
  {
    alpha2: "LR",
    alpha3: "LBR",
    countryCallingCodes: ["+231"],
    currencies: ["LRD"],
    emoji: "🇱🇷",
    ioc: "LBR",
    languages: ["eng"],
    title: "Liberia",
    value: "Liberia",
    status: "assigned",
  },
  {
    alpha2: "LS",
    alpha3: "LSO",
    countryCallingCodes: ["+266"],
    currencies: ["LSL", "ZAR"],
    emoji: "🇱🇸",
    ioc: "LES",
    languages: ["eng", "sot"],
    title: "Lesotho",
    value: "Lesotho",
    status: "assigned",
  },
  {
    alpha2: "LT",
    alpha3: "LTU",
    countryCallingCodes: ["+370"],
    currencies: ["EUR"],
    emoji: "🇱🇹",
    ioc: "LTU",
    languages: ["lit"],
    title: "Lithuania",
    value: "Lithuania",
    status: "assigned",
  },
  {
    alpha2: "LU",
    alpha3: "LUX",
    countryCallingCodes: ["+352"],
    currencies: ["EUR"],
    emoji: "🇱🇺",
    ioc: "LUX",
    languages: ["fra", "deu", "ltz"],
    title: "Luxembourg",
    value: "Luxembourg",
    status: "assigned",
  },
  {
    alpha2: "LV",
    alpha3: "LVA",
    countryCallingCodes: ["+371"],
    currencies: ["EUR"],
    emoji: "🇱🇻",
    ioc: "LAT",
    languages: ["lav"],
    title: "Latvia",
    value: "Latvia",
    status: "assigned",
  },
  {
    alpha2: "LY",
    alpha3: "LBY",
    countryCallingCodes: ["+218"],
    currencies: ["LYD"],
    emoji: "🇱🇾",
    ioc: "LBA",
    languages: ["ara"],
    title: "Libya",
    value: "Libya",
    status: "assigned",
  },
  {
    alpha2: "MA",
    alpha3: "MAR",
    countryCallingCodes: ["+212"],
    currencies: ["MAD"],
    emoji: "🇲🇦",
    ioc: "MAR",
    languages: ["ara"],
    title: "Morocco",
    value: "Morocco",
    status: "assigned",
  },
  {
    alpha2: "MC",
    alpha3: "MCO",
    countryCallingCodes: ["+377"],
    currencies: ["EUR"],
    emoji: "🇲🇨",
    ioc: "MON",
    languages: ["fra"],
    title: "Monaco",
    value: "Monaco",
    status: "assigned",
  },
  {
    alpha2: "MD",
    alpha3: "MDA",
    countryCallingCodes: ["+373"],
    currencies: ["MDL"],
    emoji: "🇲🇩",
    ioc: "MDA",
    languages: ["ron"],
    title: "Moldova",
    value: "Moldova",
    status: "assigned",
  },
  {
    alpha2: "ME",
    alpha3: "MNE",
    countryCallingCodes: ["+382"],
    currencies: ["EUR"],
    emoji: "🇲🇪",
    ioc: "MNE",
    languages: ["mot"],
    title: "Montenegro",
    value: "Montenegro",
    status: "assigned",
  },
  {
    alpha2: "MF",
    alpha3: "MAF",
    countryCallingCodes: ["+590"],
    currencies: ["EUR"],
    emoji: "🇲🇫",
    ioc: "",
    languages: ["fra"],
    title: "Saint Martin",
    value: "Saint Martin",
    status: "assigned",
  },
  {
    alpha2: "MG",
    alpha3: "MDG",
    countryCallingCodes: ["+261"],
    currencies: ["MGA"],
    emoji: "🇲🇬",
    ioc: "MAD",
    languages: ["fra", "mlg"],
    title: "Madagascar",
    value: "Madagascar",
    status: "assigned",
  },
  {
    alpha2: "MH",
    alpha3: "MHL",
    countryCallingCodes: ["+692"],
    currencies: ["USD"],
    emoji: "🇲🇭",
    ioc: "MHL",
    languages: ["eng", "mah"],
    title: "Marshall Islands",
    value: "Marshall Islands",
    status: "assigned",
  },

  {
    alpha2: "MK",
    alpha3: "MKD",
    countryCallingCodes: ["+389"],
    currencies: ["MKD"],
    emoji: "🇲🇰",
    ioc: "MKD",
    languages: ["mkd"],
    title: "Macedonia, The Former Yugoslav Republic Of",
    value: "Macedonia, The Former Yugoslav Republic Of",
    status: "assigned",
  },
  {
    alpha2: "ML",
    alpha3: "MLI",
    countryCallingCodes: ["+223"],
    currencies: ["XOF"],
    emoji: "🇲🇱",
    ioc: "MLI",
    languages: ["fra"],
    title: "Mali",
    value: "Mali",
    status: "assigned",
  },
  {
    alpha2: "MM",
    alpha3: "MMR",
    countryCallingCodes: ["+95"],
    currencies: ["MMK"],
    emoji: "🇲🇲",
    ioc: "MYA",
    languages: ["mya"],
    title: "Myanmar",
    value: "Myanmar",
    status: "assigned",
  },
  {
    alpha2: "MN",
    alpha3: "MNG",
    countryCallingCodes: ["+976"],
    currencies: ["MNT"],
    emoji: "🇲🇳",
    ioc: "MGL",
    languages: ["mon"],
    title: "Mongolia",
    value: "Mongolia",
    status: "assigned",
  },
  {
    alpha2: "MO",
    alpha3: "MAC",
    countryCallingCodes: ["+853"],
    currencies: ["MOP"],
    emoji: "🇲🇴",
    ioc: "MAC",
    languages: ["zho", "por"],
    title: "Macao",
    value: "Macao",
    status: "assigned",
  },
  {
    alpha2: "MP",
    alpha3: "MNP",
    countryCallingCodes: ["+1 670"],
    currencies: ["USD"],
    emoji: "🇲🇵",
    ioc: "",
    languages: ["eng"],
    title: "Northern Mariana Islands",
    value: "Northern Mariana Islands",
    status: "assigned",
  },
  {
    alpha2: "MQ",
    alpha3: "MTQ",
    countryCallingCodes: ["+596"],
    currencies: ["EUR"],
    emoji: "🇲🇶",
    ioc: "",
    languages: [],
    title: "Martinique",
    value: "Martinique",
    status: "assigned",
  },
  {
    alpha2: "MR",
    alpha3: "MRT",
    countryCallingCodes: ["+222"],
    currencies: ["MRO"],
    emoji: "🇲🇷",
    ioc: "MTN",
    languages: ["ara", "fra"],
    title: "Mauritania",
    value: "Mauritania",
    status: "assigned",
  },
  {
    alpha2: "MS",
    alpha3: "MSR",
    countryCallingCodes: ["+1 664"],
    currencies: ["XCD"],
    emoji: "🇲🇸",
    ioc: "",
    languages: [],
    title: "Montserrat",
    value: "Montserrat",
    status: "assigned",
  },
  {
    alpha2: "MT",
    alpha3: "MLT",
    countryCallingCodes: ["+356"],
    currencies: ["EUR"],
    emoji: "🇲🇹",
    ioc: "MLT",
    languages: ["mlt", "eng"],
    title: "Malta",
    value: "Malta",
    status: "assigned",
  },
  {
    alpha2: "MU",
    alpha3: "MUS",
    countryCallingCodes: ["+230"],
    currencies: ["MUR"],
    emoji: "🇲🇺",
    ioc: "MRI",
    languages: ["eng", "fra"],
    title: "Mauritius",
    value: "Mauritius",
    status: "assigned",
  },
  {
    alpha2: "MV",
    alpha3: "MDV",
    countryCallingCodes: ["+960"],
    currencies: ["MVR"],
    emoji: "🇲🇻",
    ioc: "MDV",
    languages: ["div"],
    title: "Maldives",
    value: "Maldives",
    status: "assigned",
  },
  {
    alpha2: "MW",
    alpha3: "MWI",
    countryCallingCodes: ["+265"],
    currencies: ["MWK"],
    emoji: "🇲🇼",
    ioc: "MAW",
    languages: ["eng", "nya"],
    title: "Malawi",
    value: "Malawi",
    status: "assigned",
  },
  {
    alpha2: "MX",
    alpha3: "MEX",
    countryCallingCodes: ["+52"],
    currencies: ["MXN", "MXV"],
    emoji: "🇲🇽",
    ioc: "MEX",
    languages: ["spa"],
    title: "Mexico",
    value: "Mexico",
    status: "assigned",
  },
  {
    alpha2: "MY",
    alpha3: "MYS",
    countryCallingCodes: ["+60"],
    currencies: ["MYR"],
    emoji: "🇲🇾",
    ioc: "MAS",
    languages: ["msa", "eng"],
    title: "Malaysia",
    value: "Malaysia",
    status: "assigned",
  },
  {
    alpha2: "MZ",
    alpha3: "MOZ",
    countryCallingCodes: ["+258"],
    currencies: ["MZN"],
    emoji: "🇲🇿",
    ioc: "MOZ",
    languages: ["por"],
    title: "Mozambique",
    value: "Mozambique",
    status: "assigned",
  },
  {
    alpha2: "NA",
    alpha3: "NAM",
    countryCallingCodes: ["+264"],
    currencies: ["NAD", "ZAR"],
    emoji: "🇳🇦",
    ioc: "NAM",
    languages: ["eng"],
    title: "Namibia",
    value: "Namibia",
    status: "assigned",
  },
  {
    alpha2: "NC",
    alpha3: "NCL",
    countryCallingCodes: ["+687"],
    currencies: ["XPF"],
    emoji: "🇳🇨",
    ioc: "",
    languages: ["fra"],
    title: "New Caledonia",
    value: "New Caledonia",
    status: "assigned",
  },
  {
    alpha2: "NE",
    alpha3: "NER",
    countryCallingCodes: ["+227"],
    currencies: ["XOF"],
    emoji: "🇳🇪",
    ioc: "NIG",
    languages: ["fra"],
    title: "Niger",
    value: "Niger",
    status: "assigned",
  },
  {
    alpha2: "NF",
    alpha3: "NFK",
    countryCallingCodes: ["+672"],
    currencies: ["AUD"],
    emoji: "🇳🇫",
    ioc: "",
    languages: ["eng"],
    title: "Norfolk Island",
    value: "Norfolk Island",
    status: "assigned",
  },
  {
    alpha2: "NG",
    alpha3: "NGA",
    countryCallingCodes: ["+234"],
    currencies: ["NGN"],
    emoji: "🇳🇬",
    ioc: "NGR",
    languages: ["eng"],
    title: "Nigeria",
    value: "Nigeria",
    status: "assigned",
  },
  {
    alpha2: "NI",
    alpha3: "NIC",
    countryCallingCodes: ["+505"],
    currencies: ["NIO"],
    emoji: "🇳🇮",
    ioc: "NCA",
    languages: ["spa"],
    title: "Nicaragua",
    value: "Nicaragua",
    status: "assigned",
  },
  {
    alpha2: "NL",
    alpha3: "NLD",
    countryCallingCodes: ["+31"],
    currencies: ["EUR"],
    emoji: "🇳🇱",
    ioc: "NED",
    languages: ["nld"],
    title: "Netherlands",
    value: "Netherlands",
    status: "assigned",
  },
  {
    alpha2: "NO",
    alpha3: "NOR",
    countryCallingCodes: ["+47"],
    currencies: ["NOK"],
    emoji: "🇳🇴",
    ioc: "NOR",
    languages: ["nor"],
    title: "Norway",
    value: "Norway",
    status: "assigned",
  },
  {
    alpha2: "NP",
    alpha3: "NPL",
    countryCallingCodes: ["+977"],
    currencies: ["NPR"],
    emoji: "🇳🇵",
    ioc: "NEP",
    languages: ["nep"],
    title: "Nepal",
    value: "Nepal",
    status: "assigned",
  },

  {
    alpha2: "NR",
    alpha3: "NRU",
    countryCallingCodes: ["+674"],
    currencies: ["AUD"],
    emoji: "🇳🇷",
    ioc: "NRU",
    languages: ["eng", "nau"],
    title: "Nauru",
    value: "Nauru",
    status: "assigned",
  },

  {
    alpha2: "NU",
    alpha3: "NIU",
    countryCallingCodes: ["+683"],
    currencies: ["NZD"],
    emoji: "🇳🇺",
    ioc: "",
    languages: ["eng"],
    title: "Niue",
    value: "Niue",
    status: "assigned",
  },
  {
    alpha2: "NZ",
    alpha3: "NZL",
    countryCallingCodes: ["+64"],
    currencies: ["NZD"],
    emoji: "🇳🇿",
    ioc: "NZL",
    languages: ["eng"],
    title: "New Zealand",
    value: "New Zealand",
    status: "assigned",
  },
  {
    alpha2: "OM",
    alpha3: "OMN",
    countryCallingCodes: ["+968"],
    currencies: ["OMR"],
    emoji: "🇴🇲",
    ioc: "OMA",
    languages: ["ara"],
    title: "Oman",
    value: "Oman",
    status: "assigned",
  },
  {
    alpha2: "PA",
    alpha3: "PAN",
    countryCallingCodes: ["+507"],
    currencies: ["PAB", "USD"],
    emoji: "🇵🇦",
    ioc: "PAN",
    languages: ["spa"],
    title: "Panama",
    value: "Panama",
    status: "assigned",
  },

  {
    alpha2: "PE",
    alpha3: "PER",
    countryCallingCodes: ["+51"],
    currencies: ["PEN"],
    emoji: "🇵🇪",
    ioc: "PER",
    languages: ["spa", "aym", "que"],
    title: "Peru",
    value: "Peru",
    status: "assigned",
  },
  {
    alpha2: "PF",
    alpha3: "PYF",
    countryCallingCodes: ["+689"],
    currencies: ["XPF"],
    emoji: "🇵🇫",
    ioc: "",
    languages: ["fra"],
    title: "French Polynesia",
    value: "French Polynesia",
    status: "assigned",
  },
  {
    alpha2: "PG",
    alpha3: "PNG",
    countryCallingCodes: ["+675"],
    currencies: ["PGK"],
    emoji: "🇵🇬",
    ioc: "PNG",
    languages: ["eng"],
    title: "Papua New Guinea",
    value: "Papua New Guinea",
    status: "assigned",
  },
  {
    alpha2: "PH",
    alpha3: "PHL",
    countryCallingCodes: ["+63"],
    currencies: ["PHP"],
    emoji: "🇵🇭",
    ioc: "PHI",
    languages: ["eng"],
    title: "Philippines",
    value: "Philippines",
    status: "assigned",
  },
  {
    alpha2: "PK",
    alpha3: "PAK",
    countryCallingCodes: ["+92"],
    currencies: ["PKR"],
    emoji: "🇵🇰",
    ioc: "PAK",
    languages: ["urd", "eng"],
    title: "Pakistan",
    value: "Pakistan",
    status: "assigned",
  },
  {
    alpha2: "PL",
    alpha3: "POL",
    countryCallingCodes: ["+48"],
    currencies: ["PLN"],
    emoji: "🇵🇱",
    ioc: "POL",
    languages: ["pol"],
    title: "Poland",
    value: "Poland",
    status: "assigned",
  },
  {
    alpha2: "PM",
    alpha3: "SPM",
    countryCallingCodes: ["+508"],
    currencies: ["EUR"],
    emoji: "🇵🇲",
    ioc: "",
    languages: ["eng"],
    title: "Saint Pierre And Miquelon",
    value: "Saint Pierre And Miquelon",
    status: "assigned",
  },
  {
    alpha2: "PN",
    alpha3: "PCN",
    countryCallingCodes: ["+872"],
    currencies: ["NZD"],
    emoji: "🇵🇳",
    ioc: "",
    languages: ["eng"],
    title: "Pitcairn",
    value: "Pitcairn",
    status: "assigned",
  },
  {
    alpha2: "PR",
    alpha3: "PRI",
    countryCallingCodes: ["+1 787", "+1 939"],
    currencies: ["USD"],
    emoji: "🇵🇷",
    ioc: "PUR",
    languages: ["spa", "eng"],
    title: "Puerto Rico",
    value: "Puerto Rico",
    status: "assigned",
  },
  {
    alpha2: "PS",
    alpha3: "PSE",
    countryCallingCodes: ["+970"],
    currencies: ["JOD", "EGP", "ILS"],
    emoji: "🇵🇸",
    ioc: "PLE",
    languages: ["ara"],
    title: "Palestinian Territory, Occupied",
    value: "Palestinian Territory, Occupied",
    status: "assigned",
  },
  {
    alpha2: "PT",
    alpha3: "PRT",
    countryCallingCodes: ["+351"],
    currencies: ["EUR"],
    emoji: "🇵🇹",
    ioc: "POR",
    languages: ["por"],
    title: "Portugal",
    value: "Portugal",
    status: "assigned",
  },

  {
    alpha2: "PW",
    alpha3: "PLW",
    countryCallingCodes: ["+680"],
    currencies: ["USD"],
    emoji: "🇵🇼",
    ioc: "PLW",
    languages: ["eng"],
    title: "Palau",
    value: "Palau",
    status: "assigned",
  },
  {
    alpha2: "PY",
    alpha3: "PRY",
    countryCallingCodes: ["+595"],
    currencies: ["PYG"],
    emoji: "🇵🇾",
    ioc: "PAR",
    languages: ["spa"],
    title: "Paraguay",
    value: "Paraguay",
    status: "assigned",
  },

  {
    alpha2: "QA",
    alpha3: "QAT",
    countryCallingCodes: ["+974"],
    currencies: ["QAR"],
    emoji: "🇶🇦",
    ioc: "QAT",
    languages: ["ara"],
    title: "Qatar",
    value: "Qatar",
    status: "assigned",
  },
  {
    alpha2: "RE",
    alpha3: "REU",
    countryCallingCodes: ["+262"],
    currencies: ["EUR"],
    emoji: "🇷🇪",
    ioc: "",
    languages: ["fra"],
    title: "Reunion",
    value: "Reunion",
    status: "assigned",
  },

  {
    alpha2: "RO",
    alpha3: "ROU",
    countryCallingCodes: ["+40"],
    currencies: ["RON"],
    emoji: "🇷🇴",
    ioc: "ROU",
    languages: ["ron"],
    title: "Romania",
    value: "Romania",
    status: "assigned",
  },
  {
    alpha2: "RS",
    alpha3: "SRB",
    countryCallingCodes: ["+381"],
    currencies: ["RSD"],
    emoji: "🇷🇸",
    ioc: "SRB",
    languages: ["srp"],
    title: "Serbia",
    value: "Serbia",
    status: "assigned",
  },
  {
    alpha2: "RU",
    alpha3: "RUS",
    countryCallingCodes: ["+7", "+7 3", "+7 4", "+7 8"],
    currencies: ["RUB"],
    emoji: "🇷🇺",
    ioc: "RUS",
    languages: ["rus"],
    title: "Russia",
    value: "Russia",
    status: "assigned",
  },
  {
    alpha2: "RW",
    alpha3: "RWA",
    countryCallingCodes: ["+250"],
    currencies: ["RWF"],
    emoji: "🇷🇼",
    ioc: "RWA",
    languages: ["eng", "fra", "kin"],
    title: "Rwanda",
    value: "Rwanda",
    status: "assigned",
  },
  {
    alpha2: "SA",
    alpha3: "SAU",
    countryCallingCodes: ["+966"],
    currencies: ["SAR"],
    emoji: "🇸🇦",
    ioc: "KSA",
    languages: ["ara"],
    title: "Saudi Arabia",
    value: "Saudi Arabia",
    status: "assigned",
  },
  {
    alpha2: "SB",
    alpha3: "SLB",
    countryCallingCodes: ["+677"],
    currencies: ["SBD"],
    emoji: "🇸🇧",
    ioc: "SOL",
    languages: ["eng"],
    title: "Solomon Islands",
    value: "Solomon Islands",
    status: "assigned",
  },
  {
    alpha2: "SC",
    alpha3: "SYC",
    countryCallingCodes: ["+248"],
    currencies: ["SCR"],
    emoji: "🇸🇨",
    ioc: "SEY",
    languages: ["eng", "fra"],
    title: "Seychelles",
    value: "Seychelles",
    status: "assigned",
  },
  {
    alpha2: "SD",
    alpha3: "SDN",
    countryCallingCodes: ["+249"],
    currencies: ["SDG"],
    emoji: "🇸🇩",
    ioc: "SUD",
    languages: ["ara", "eng"],
    title: "Sudan",
    value: "Sudan",
    status: "assigned",
  },
  {
    alpha2: "SE",
    alpha3: "SWE",
    countryCallingCodes: ["+46"],
    currencies: ["SEK"],
    emoji: "🇸🇪",
    ioc: "SWE",
    languages: ["swe"],
    title: "Sweden",
    value: "Sweden",
    status: "assigned",
  },
  {
    alpha2: "SG",
    alpha3: "SGP",
    countryCallingCodes: ["+65"],
    currencies: ["SGD"],
    emoji: "🇸🇬",
    ioc: "SIN",
    languages: ["eng", "zho", "msa", "tam"],
    title: "Singapore",
    value: "Singapore",
    status: "assigned",
  },
  {
    alpha2: "SH",
    alpha3: "SHN",
    countryCallingCodes: ["+290"],
    currencies: ["SHP"],
    emoji: "🇸🇭",
    ioc: "",
    languages: ["eng"],
    title: "Saint Helena, Ascension And Tristan Da Cunha",
    value: "Saint Helena, Ascension And Tristan Da Cunha",
    status: "assigned",
  },
  {
    alpha2: "SI",
    alpha3: "SVN",
    countryCallingCodes: ["+386"],
    currencies: ["EUR"],
    emoji: "🇸🇮",
    ioc: "SLO",
    languages: ["slv"],
    title: "Slovenia",
    value: "Slovenia",
    status: "assigned",
  },
  {
    alpha2: "SJ",
    alpha3: "SJM",
    countryCallingCodes: ["+47"],
    currencies: ["NOK"],
    emoji: "🇸🇯",
    ioc: "",
    languages: [],
    title: "Svalbard And Jan Mayen",
    value: "Svalbard And Jan Mayen",
    status: "assigned",
  },
  {
    alpha2: "SK",
    alpha3: "SVK",
    countryCallingCodes: ["+421"],
    currencies: ["EUR"],
    emoji: "🇸🇰",
    ioc: "SVK",
    languages: ["slk"],
    title: "Slovakia",
    value: "Slovakia",
    status: "assigned",
  },
  {
    alpha2: "SL",
    alpha3: "SLE",
    countryCallingCodes: ["+232"],
    currencies: ["SLL"],
    emoji: "🇸🇱",
    ioc: "SLE",
    languages: ["eng"],
    title: "Sierra Leone",
    value: "Sierra Leone",
    status: "assigned",
  },
  {
    alpha2: "SM",
    alpha3: "SMR",
    countryCallingCodes: ["+378"],
    currencies: ["EUR"],
    emoji: "🇸🇲",
    ioc: "SMR",
    languages: ["ita"],
    title: "San Marino",
    value: "San Marino",
    status: "assigned",
  },
  {
    alpha2: "SN",
    alpha3: "SEN",
    countryCallingCodes: ["+221"],
    currencies: ["XOF"],
    emoji: "🇸🇳",
    ioc: "SEN",
    languages: ["fra"],
    title: "Senegal",
    value: "Senegal",
    status: "assigned",
  },
  {
    alpha2: "SO",
    alpha3: "SOM",
    countryCallingCodes: ["+252"],
    currencies: ["SOS"],
    emoji: "🇸🇴",
    ioc: "SOM",
    languages: ["som"],
    title: "Somalia",
    value: "Somalia",
    status: "assigned",
  },
  {
    alpha2: "SR",
    alpha3: "SUR",
    countryCallingCodes: ["+597"],
    currencies: ["SRD"],
    emoji: "🇸🇷",
    ioc: "SUR",
    languages: ["nld"],
    title: "Suriname",
    value: "Suriname",
    status: "assigned",
  },
  {
    alpha2: "SS",
    alpha3: "SSD",
    countryCallingCodes: ["+211"],
    currencies: ["SSP"],
    emoji: "🇸🇸",
    ioc: "SSD",
    languages: ["eng"],
    title: "South Sudan",
    value: "South Sudan",
    status: "assigned",
  },
  {
    alpha2: "ST",
    alpha3: "STP",
    countryCallingCodes: ["+239"],
    currencies: ["STD"],
    emoji: "🇸🇹",
    ioc: "STP",
    languages: ["por"],
    title: "Sao Tome and Principe",
    value: "Sao Tome and Principe",
    status: "assigned",
  },
  {
    alpha2: "SV",
    alpha3: "SLV",
    countryCallingCodes: ["+503"],
    currencies: ["USD"],
    emoji: "🇸🇻",
    ioc: "ESA",
    languages: ["spa"],
    title: "El Salvador",
    value: "El Salvador",
    status: "assigned",
  },
  {
    alpha2: "SX",
    alpha3: "SXM",
    countryCallingCodes: ["+1 721"],
    currencies: ["ANG"],
    emoji: "🇸🇽",
    ioc: "",
    languages: ["nld"],
    title: "Sint Maarten",
    value: "Sint Maarten",
    status: "assigned",
  },
  {
    alpha2: "SY",
    alpha3: "SYR",
    countryCallingCodes: ["+963"],
    currencies: ["SYP"],
    emoji: "🇸🇾",
    ioc: "SYR",
    languages: ["ara"],
    title: "Syrian Arab Republic",
    value: "Syrian Arab Republic",
    status: "assigned",
  },
  {
    alpha2: "SZ",
    alpha3: "SWZ",
    countryCallingCodes: ["+268"],
    currencies: ["SZL"],
    emoji: "🇸🇿",
    ioc: "SWZ",
    languages: ["eng", "ssw"],
    title: "Swaziland",
    value: "Swaziland",
    status: "assigned",
  },
  {
    alpha2: "TC",
    alpha3: "TCA",
    countryCallingCodes: ["+1 649"],
    currencies: ["USD"],
    emoji: "🇹🇨",
    ioc: "",
    languages: ["eng"],
    title: "Turks And Caicos Islands",
    value: "Turks And Caicos Islands",
    status: "assigned",
  },
  {
    alpha2: "TD",
    alpha3: "TCD",
    countryCallingCodes: ["+235"],
    currencies: ["XAF"],
    emoji: "🇹🇩",
    ioc: "CHA",
    languages: ["ara", "fra"],
    title: "Chad",
    value: "Chad",
    status: "assigned",
  },
  {
    alpha2: "TF",
    alpha3: "ATF",
    countryCallingCodes: [],
    currencies: ["EUR"],
    emoji: "🇹🇫",
    ioc: "",
    languages: ["fra"],
    title: "French Southern Territories",
    value: "French Southern Territories",
    status: "assigned",
  },
  {
    alpha2: "TG",
    alpha3: "TGO",
    countryCallingCodes: ["+228"],
    currencies: ["XOF"],
    emoji: "🇹🇬",
    ioc: "TOG",
    languages: ["fra"],
    title: "Togo",
    value: "Togo",
    status: "assigned",
  },
  {
    alpha2: "TH",
    alpha3: "THA",
    countryCallingCodes: ["+66"],
    currencies: ["THB"],
    emoji: "🇹🇭",
    ioc: "THA",
    languages: ["tha"],
    title: "Thailand",
    value: "Thailand",
    status: "assigned",
  },
  {
    alpha2: "TJ",
    alpha3: "TJK",
    countryCallingCodes: ["+992"],
    currencies: ["TJS"],
    emoji: "🇹🇯",
    ioc: "TJK",
    languages: ["tgk", "rus"],
    title: "Tajikistan",
    value: "Tajikistan",
    status: "assigned",
  },
  {
    alpha2: "TK",
    alpha3: "TKL",
    countryCallingCodes: ["+690"],
    currencies: ["NZD"],
    emoji: "🇹🇰",
    ioc: "",
    languages: ["eng"],
    title: "Tokelau",
    value: "Tokelau",
    status: "assigned",
  },
  {
    alpha2: "TL",
    alpha3: "TLS",
    countryCallingCodes: ["+670"],
    currencies: ["USD"],
    emoji: "🇹🇱",
    ioc: "TLS",
    languages: ["por"],
    title: "Timor-Leste, Democratic Republic of",
    value: "Timor-Leste, Democratic Republic of",
    status: "assigned",
  },
  {
    alpha2: "TM",
    alpha3: "TKM",
    countryCallingCodes: ["+993"],
    currencies: ["TMT"],
    emoji: "🇹🇲",
    ioc: "TKM",
    languages: ["tuk", "rus"],
    title: "Turkmenistan",
    value: "Turkmenistan",
    status: "assigned",
  },
  {
    alpha2: "TN",
    alpha3: "TUN",
    countryCallingCodes: ["+216"],
    currencies: ["TND"],
    emoji: "🇹🇳",
    ioc: "TUN",
    languages: ["ara"],
    title: "Tunisia",
    value: "Tunisia",
    status: "assigned",
  },
  {
    alpha2: "TO",
    alpha3: "TON",
    countryCallingCodes: ["+676"],
    currencies: ["TOP"],
    emoji: "🇹🇴",
    ioc: "TGA",
    languages: ["eng"],
    title: "Tonga",
    value: "Tonga",
    status: "assigned",
  },

  {
    alpha2: "TR",
    alpha3: "TUR",
    countryCallingCodes: ["+90"],
    currencies: ["TRY"],
    emoji: "🇹🇷",
    ioc: "TUR",
    languages: ["tur"],
    title: "Turkey",
    value: "Turkey",
    status: "assigned",
  },
  {
    alpha2: "TT",
    alpha3: "TTO",
    countryCallingCodes: ["+1 868"],
    currencies: ["TTD"],
    emoji: "🇹🇹",
    ioc: "TTO",
    languages: ["eng"],
    title: "Trinidad And Tobago",
    value: "Trinidad And Tobago",
    status: "assigned",
  },
  {
    alpha2: "TV",
    alpha3: "TUV",
    countryCallingCodes: ["+688"],
    currencies: ["AUD"],
    emoji: "🇹🇻",
    ioc: "TUV",
    languages: ["eng"],
    title: "Tuvalu",
    value: "Tuvalu",
    status: "assigned",
  },
  {
    alpha2: "TW",
    alpha3: "TWN",
    countryCallingCodes: ["+886"],
    currencies: ["TWD"],
    emoji: "🇹🇼",
    ioc: "TPE",
    languages: ["zho"],
    title: "Taiwan",
    value: "Taiwan",
    status: "assigned",
  },
  {
    alpha2: "TZ",
    alpha3: "TZA",
    countryCallingCodes: ["+255"],
    currencies: ["TZS"],
    emoji: "🇹🇿",
    ioc: "TAN",
    languages: ["swa", "eng"],
    title: "Tanzania, United Republic Of",
    value: "Tanzania, United Republic Of",
    status: "assigned",
  },
  {
    alpha2: "UA",
    alpha3: "UKR",
    countryCallingCodes: ["+380"],
    currencies: ["UAH"],
    emoji: "🇺🇦",
    ioc: "UKR",
    languages: ["ukr", "rus"],
    title: "Ukraine",
    value: "Ukraine",
    status: "assigned",
  },
  {
    alpha2: "UG",
    alpha3: "UGA",
    countryCallingCodes: ["+256"],
    currencies: ["UGX"],
    emoji: "🇺🇬",
    ioc: "UGA",
    languages: ["eng", "swa"],
    title: "Uganda",
    value: "Uganda",
    status: "assigned",
  },
  {
    alpha2: "UM",
    alpha3: "UMI",
    countryCallingCodes: ["+1"],
    currencies: ["USD"],
    emoji: "🇺🇲",
    ioc: "",
    languages: ["eng"],
    title: "United States Minor Outlying Islands",
    value: "United States Minor Outlying Islands",
    status: "assigned",
  },
  {
    alpha2: "US",
    alpha3: "USA",
    countryCallingCodes: ["+1"],
    currencies: ["USD"],
    emoji: "🇺🇸",
    ioc: "USA",
    languages: ["eng"],
    title: "United States",
    value: "United States",
    status: "assigned",
  },
  {
    alpha2: "UY",
    alpha3: "URY",
    countryCallingCodes: ["+598"],
    currencies: ["UYU", "UYI"],
    emoji: "🇺🇾",
    ioc: "URU",
    languages: ["spa"],
    title: "Uruguay",
    value: "Uruguay",
    status: "assigned",
  },
  {
    alpha2: "UZ",
    alpha3: "UZB",
    countryCallingCodes: ["+998"],
    currencies: ["UZS"],
    emoji: "🇺🇿",
    ioc: "UZB",
    languages: ["uzb", "rus"],
    title: "Uzbekistan",
    value: "Uzbekistan",
    status: "assigned",
  },
  {
    alpha2: "VA",
    alpha3: "VAT",
    countryCallingCodes: ["+379", "+39"],
    currencies: ["EUR"],
    emoji: "🇻🇦",
    ioc: "",
    languages: ["ita"],
    title: "Vatican City State",
    value: "Vatican City State",
    status: "assigned",
  },
  {
    alpha2: "VC",
    alpha3: "VCT",
    countryCallingCodes: ["+1 784"],
    currencies: ["XCD"],
    emoji: "🇻🇨",
    ioc: "VIN",
    languages: ["eng"],
    title: "Saint Vincent And The Grenadines",
    value: "Saint Vincent And The Grenadines",
    status: "assigned",
  },

  {
    alpha2: "VE",
    alpha3: "VEN",
    countryCallingCodes: ["+58"],
    currencies: ["VEF"],
    emoji: "🇻🇪",
    ioc: "VEN",
    languages: ["spa"],
    title: "Venezuela, Bolivarian Republic Of",
    value: "Venezuela, Bolivarian Republic Of",
    status: "assigned",
  },
  {
    alpha2: "VG",
    alpha3: "VGB",
    countryCallingCodes: ["+1 284"],
    currencies: ["USD"],
    emoji: "🇻🇬",
    ioc: "IVB",
    languages: ["eng"],
    title: "Virgin Islands (British)",
    value: "Virgin Islands (British)",
    status: "assigned",
  },
  {
    alpha2: "VI",
    alpha3: "VIR",
    countryCallingCodes: ["+1 340"],
    currencies: ["USD"],
    emoji: "🇻🇮",
    ioc: "ISV",
    languages: ["eng"],
    title: "Virgin Islands (US)",
    value: "Virgin Islands (US)",
    status: "assigned",
  },
  {
    alpha2: "VN",
    alpha3: "VNM",
    countryCallingCodes: ["+84"],
    currencies: ["VND"],
    emoji: "🇻🇳",
    ioc: "VIE",
    languages: ["vie"],
    title: "VietNam",
    value: "VietNam",
    status: "assigned",
  },
  {
    alpha2: "VU",
    alpha3: "VUT",
    countryCallingCodes: ["+678"],
    currencies: ["VUV"],
    emoji: "🇻🇺",
    ioc: "VAN",
    languages: ["bis", "eng", "fra"],
    title: "Vanuatu",
    value: "Vanuatu",
    status: "assigned",
  },
  {
    alpha2: "WF",
    alpha3: "WLF",
    countryCallingCodes: ["+681"],
    currencies: ["XPF"],
    emoji: "🇼🇫",
    ioc: "",
    languages: ["fra"],
    title: "Wallis And Futuna",
    value: "Wallis And Futuna",
    status: "assigned",
  },

  {
    alpha2: "WS",
    alpha3: "WSM",
    countryCallingCodes: ["+685"],
    currencies: ["WST"],
    emoji: "🇼🇸",
    ioc: "SAM",
    languages: ["eng", "smo"],
    title: "Samoa",
    value: "Samoa",
    status: "assigned",
  },
  {
    alpha2: "XK",
    alpha3: "",
    countryCallingCodes: ["+383"],
    currencies: ["EUR"],
    emoji: "",
    ioc: "KOS",
    languages: ["sqi", "srp", "bos", "tur", "rom"],
    title: "Kosovo",
    value: "Kosovo",
    status: "user assigned",
  },

  {
    alpha2: "YE",
    alpha3: "YEM",
    countryCallingCodes: ["+967"],
    currencies: ["YER"],
    emoji: "🇾🇪",
    ioc: "YEM",
    languages: ["ara"],
    title: "Yemen",
    value: "Yemen",
    status: "assigned",
  },
  {
    alpha2: "YT",
    alpha3: "MYT",
    countryCallingCodes: ["+262"],
    currencies: ["EUR"],
    emoji: "🇾🇹",
    ioc: "",
    languages: ["fra"],
    title: "Mayotte",
    value: "Mayotte",
    status: "assigned",
  },
  {
    alpha2: "ZA",
    alpha3: "ZAF",
    countryCallingCodes: ["+27"],
    currencies: ["ZAR"],
    emoji: "🇿🇦",
    ioc: "RSA",
    languages: ["afr", "eng", "nbl", "som", "tso", "ven", "xho", "zul"],
    title: "South Africa",
    value: "South Africa",
    status: "assigned",
  },
  {
    alpha2: "ZM",
    alpha3: "ZMB",
    countryCallingCodes: ["+260"],
    currencies: ["ZMW"],
    emoji: "🇿🇲",
    ioc: "ZAM",
    languages: ["eng"],
    title: "Zambia",
    value: "Zambia",
    status: "assigned",
  },
  {
    alpha2: "ZW",
    alpha3: "ZWE",
    countryCallingCodes: ["+263"],
    currencies: ["USD", "ZAR", "BWP", "GBP", "EUR"],
    emoji: "🇿🇼",
    ioc: "ZIM",
    languages: ["eng", "sna", "nde"],
    title: "Zimbabwe",
    value: "Zimbabwe",
    status: "assigned",
  },
];
